# Generated by Django 2.2.1 on 2019-06-02 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminderdescription', models.TextField(blank=True)),
                ('remindertime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('reminderdue', models.DateTimeField()),
            ],
        ),
    ]
