# Generated by Django 2.2.1 on 2019-06-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_reminder_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
